force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <pluralLabel>Job Applications</pluralLabel>
    <nameField>
        <label>Application Number</label>
        <type>AutoNumber</type>
        <displayFormat>APP-{00000}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job Posting</label>
    <type>Lookup</type>
    <required>true</required>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <deleteConstraint>Restrict</deleteConstraint>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>JP-{0000}</displayFormat>
        <label>Job Posting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerTest.cls
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
@IsTest(testFor='ApexTrigger:JobApplicationTrigger')
private class JobApplicationTriggerTest {
  @IsTest
  private static void shouldBeAbleToPerformDml() {
    TriggerBase.bypass(Schema.Contact.SObjectType);
    Contact janeCoder = new Contact(
      FirstName = 'Jane',
      LastName = 'Coder',
      Email = 'Jane@example.com'
    );
    insert janeCoder;
    TriggerBase.clearBypass(Schema.Contact.SObjectType);

    TriggerBase.bypass(Schema.Job_Posting__c.SObjectType);
    Job_Posting__c posting = new Job_Posting__c(
      Title__c = 'Director of Product Management',
      Location__c = 'San Francisco',
      Description__c = 'Help Salesforce to make the next generation of developer tooling',
      ExternalID__c = 'Job_12345'
    );
    insert posting;
    TriggerBase.clearBypass(Schema.Job_Posting__c.SObjectType);

    try {
      TriggerBase.bypass(Schema.Job_Application__c.SObjectType);
      Job_Application__c application = new Job_Application__c(
        Candidate__c = janeCoder.Id,
        Job_Posting__c = posting.Id,
        Years_of_Experience__c = 12
      );
      insert application;
    } catch (Exception e) {
      System.Assert.fail(
        'There should be no problems when performing DML on a "Job_Application__c" record.'
      );
    }
  }
}