force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>JP-{0000}</displayFormat>
        <label>Job Posting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobPostingTriggerTest.cls
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
@IsTest(testFor='ApexTrigger:JobPostingTrigger')
private class JobPostingTriggerTest {
  @IsTest
  private static void shouldBeAbleToPerformDml() {
    try {
      TriggerBase.bypass(Schema.Job_Posting__c.SObjectType);
      insert new Job_Posting__c(
        Title__c = 'Director of Product Management',
        Location__c = 'San Francisco',
        Description__c = 'Help Salesforce to make the next generation of developer tooling',
        ExternalID__c = 'Job_12345'
      );
    } catch (Exception e) {
      System.Assert.fail(
        'There should be no problems when performing DML on a "Job_Posting__c" record.'
      );
    }
  }
}